export const VALIDATION_CRITERIA_IDS = {
  OVERLAPPING: 3,
  SELF: 4,
  COORDINATE_SYSTEM: 5,
  SIZE: 6,
  WITHIN_COUNTRY: 7,
  SPIKE: 8,
  GEOMETRY_TYPE: 10,
  ESTIMATED_AREA: 12,
  SCHEMA: 13,
  DATA: 14,
  PLANT_START_DATE: 15
} as const;

export type ValidationCriteriaId = (typeof VALIDATION_CRITERIA_IDS)[keyof typeof VALIDATION_CRITERIA_IDS];

export const VALIDATION_CRITERIA_NAMES = {
  [VALIDATION_CRITERIA_IDS.OVERLAPPING]: "Overlapping",
  [VALIDATION_CRITERIA_IDS.SELF]: "Self Intersection",
  [VALIDATION_CRITERIA_IDS.COORDINATE_SYSTEM]: "Coordinate System",
  [VALIDATION_CRITERIA_IDS.SIZE]: "Size",
  [VALIDATION_CRITERIA_IDS.WITHIN_COUNTRY]: "Within Country",
  [VALIDATION_CRITERIA_IDS.SPIKE]: "Spike",
  [VALIDATION_CRITERIA_IDS.GEOMETRY_TYPE]: "Geometry Type",
  [VALIDATION_CRITERIA_IDS.ESTIMATED_AREA]: "Estimated Area",
  [VALIDATION_CRITERIA_IDS.SCHEMA]: "Schema",
  [VALIDATION_CRITERIA_IDS.DATA]: "Data",
  [VALIDATION_CRITERIA_IDS.PLANT_START_DATE]: "Plant Start Date"
} as const;
