version: "3.8"

networks:
  corp:
    driver: bridge

services:
  user-service:
    container_name: user-service
    build:
      context: ./
      cache_from:
        - terramatch-microservices-base:nx-base
      dockerfile: ./apps/user-service/Dockerfile
      args:
        NODE_ENV: "production"
        BUILD_FLAG: ""
    image: user-service:nx-prod
    ports:
      - 4010:4010
    environment:
      NODE_ENV: "production"
      PORT: 4010
    networks:
      - corp
    restart: on-failure
