services:
  mariadb:
    build:
      context: "."
      dockerfile: "docker/mariadb.Dockerfile"
    ports:
      - "3360:3306"
    networks:
      - "default"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "terramatch_microservices_test"
      MYSQL_USER: "wri"
      MYSQL_PASSWORD: "wri"
networks:
  default:
