import { QueryInterface } from "sequelize";
import { RunnableMigration } from "umzug";

export const dropUnusedTables: RunnableMigration<QueryInterface> = {
  name: "202605130922-drop-unused-tables",

  async up({ context }) {
    // Remove a few tables up front to take care of some foreign key constraints
    await context.dropTable("programme_tree_species");
    await context.dropTable("satellite_maps");
    await context.dropTable("progress_updates");
    await context.dropTable("targets");
    await context.dropTable("monitorings");
    await context.dropTable("matches");
    await context.dropTable("tree_species_versions");
    await context.dropTable("tree_species");
    await context.dropTable("restoration_method_metric_versions");
    await context.dropTable("restoration_method_metrics");
    await context.dropTable("socioeconomic_benefits");
    await context.dropTable("submission_media_uploads");
    await context.dropTable("csv_imports");
    await context.dropTable("submissions");
    await context.dropTable("site_tree_species");
    await context.dropTable("site_submission_disturbances");
    await context.dropTable("site_csv_imports");
    await context.dropTable("direct_seedings");
    await context.dropTable("site_submissions");
    await context.dropTable("seed_details");
    await context.dropTable("site_restoration_method_site");
    await context.dropTable("land_tenure_site");
    await context.dropTable("invasives");
    await context.dropTable("media_uploads");
    await context.dropTable("sites");
    await context.dropTable("terrafund_tree_species");
    await context.dropTable("terrafund_sites");

    // These are all now free to drop in alphabetical order without violating constraints
    await context.dropTable("aims");
    await context.dropTable("baseline_monitoring_metrics_project");
    await context.dropTable("baseline_monitoring_metrics_site");
    await context.dropTable("carbon_certification_versions");
    await context.dropTable("carbon_certifications");
    await context.dropTable("code_criteria");
    await context.dropTable("code_indicator");
    await context.dropTable("devices");
    await context.dropTable("document_files");
    await context.dropTable("drafts");
    await context.dropTable("due_submissions");
    await context.dropTable("edit_histories");
    await context.dropTable("elevator_videos");
    await context.dropTable("filter_records");
    await context.dropTable("form_common_options");
    await context.dropTable("form_common_options_questions");
    await context.dropTable("framework_invite_codes");
    await context.dropTable("i18n_translations_bak");
    await context.dropTable("indicator_site");
    await context.dropTable("interests");
    await context.dropTable("land_tenures");
    await context.dropTable("migrations");
    await context.dropTable("model_has_permissions");
    await context.dropTable("notifications_buffer");
    await context.dropTable("offer_contacts");
    await context.dropTable("offer_documents");
    await context.dropTable("offers");
    await context.dropTable("organisation_document_versions");
    await context.dropTable("organisation_documents");
    await context.dropTable("organisation_files");
    await context.dropTable("organisation_photos");
    await context.dropTable("organisation_versions");
    await context.dropTable("pending_transitions");
    await context.dropTable("pitch_contacts");
    await context.dropTable("pitch_document_versions");
    await context.dropTable("pitch_documents");
    await context.dropTable("pitch_versions");
    await context.dropTable("pitches");
    await context.dropTable("programme_invites");
    await context.dropTable("programme_user");
    await context.dropTable("programmes");
    await context.dropTable("project_pipelines");
    await context.dropTable("satellite_monitors");
    await context.dropTable("shapefiles");
    await context.dropTable("site_polygon_local");
    await context.dropTable("site_restoration_methods");
    await context.dropTable("staging_projects_csv");
    await context.dropTable("staging_tracking_csv");
    await context.dropTable("staging_tracking_pitch_csv");
    await context.dropTable("state_histories");
    await context.dropTable("taggables");
    await context.dropTable("tags");
    await context.dropTable("team_members");
    await context.dropTable("terrafund_csv_imports");
    await context.dropTable("terrafund_disturbances");
    await context.dropTable("terrafund_due_submissions");
    await context.dropTable("terrafund_files");
    await context.dropTable("terrafund_none_tree_species");
    await context.dropTable("terrafund_nurseries");
    await context.dropTable("terrafund_nursery_submissions");
    await context.dropTable("terrafund_programme_invites");
    await context.dropTable("terrafund_programme_submissions");
    await context.dropTable("terrafund_programme_user");
    await context.dropTable("terrafund_programmes");
    await context.dropTable("terrafund_site_submissions");
    await context.dropTable("uploads");
    await context.dropTable("v2_polygons");
    await context.dropTable("v2_project_monitorings");
    await context.dropTable("v2_site_monitorings");
    await context.dropTable("v2_temporary_sites");
  }
};
