import { AirtableEntity, ColumnMapping, commonEntityColumns } from "./airtable-entity";
import { Organisation } from "@terramatch-microservices/database/entities";

const COLUMNS: ColumnMapping<Organisation>[] = [
  ...commonEntityColumns<Organisation>("organisation"),
  "status",
  "type",
  "private",
  "isTest",
  "name",
  "phone",
  "hqStreet1",
  "hqStreet2",
  "hqCity",
  "hqState",
  "hqZipcode",
  "hqCountry",
  "leadershipTeamTxt",
  "foundingDate",
  "description",
  "countries",
  "languages",
  "treeCareApproach",
  "relevantExperienceYears",
  "treesGrown3Year",
  "treesGrownTotal",
  "haRestored3Year",
  "haRestoredTotal",
  "finStartMonth",
  "finBudgetCurrentYear",
  "finBudget1Year",
  "finBudget2Year",
  "finBudget3Year",
  "webUrl",
  "facebookUrl",
  "instagramUrl",
  "linkedinUrl",
  "twitterUrl",
  "additionalFundingDetails",
  "communityExperience",
  "totalTreesGrown",
  "avgTreeSurvivalRate",
  "treeMaintenanceAftercareApproach",
  "restoredAreasDescription",
  "restorationTypesImplemented",
  "historicMonitoringGeojson",
  "monitoringEvaluationExperience",
  "fundingHistory",
  "engagementFarmers",
  "engagementWomen",
  "engagementYouth",
  "currency",
  "states",
  "district",
  "accountNumber1",
  "accountNumber2",
  "loanStatusAmount",
  "loanStatusTypes",
  "approachOfMarginalizedCommunities",
  "communityEngagementNumbersMarginalized",
  "landSystems",
  "fundUtilisation",
  "detailedInterventionTypes",
  "totalBoardMembers",
  "pctBoardWomen",
  "pctBoardMen",
  "pctBoardYouth",
  "pctBoardNonYouth",
  "engagementNonYouth",
  "treeRestorationPractices",
  "businessModel",
  "subtype",
  "organisationRevenueThisYear",
  "fieldStaffSkills",
  "fpcCompany",
  "numOfFarmersOnBoard",
  "benefactorsFpcCompany",
  "boardRemunerationFpcCompany",
  "boardEngagementFpcCompany",
  "biodiversityFocus",
  "globalPlanningFrameworks",
  "pastGovCollaboration",
  "engagementLandless",
  "socioeconomicImpact",
  "environmentalImpact",
  "growthStage",
  "additionalComments"
];

export class OrganisationEntity extends AirtableEntity<Organisation> {
  readonly TABLE_NAME = "Organisations";
  readonly COLUMNS = COLUMNS;
  readonly MODEL = Organisation;
}
