openapi: 3.1.0
info:
  title: TerraMatch Research Persona APIs
  description: |-
    The set of research persona APIs will be developed to assist the data team with fetching
    well structured data from the TerraMatch API Backend.

    https://app.asana.com/0/1206059288585913/1208023832218964/f
  version: 0.1.0
paths:
  /organisations:
    get:
  /applications:
    get:
  /projects:
    get:
  /project-reports:
    get:
  /sites:
    get:
  /sites-eports:
    get:
  /nurseries:
    get:
  /nursery-reports:
    get:
components:
  schemas:
    Organisation:
      type: object
      properties:
    Application:
      type: object
      properties:
    Project:
      type: object
      properties:
    ProjectReport:
      type: object
      properties:
    Site:
      type: object
      properties:
    SiteReport:
      type: object
      properties:
    Nursery:
      type: object
      properties:
    NurseryReport:
      type: object
      properties:


