import {
  BaseEntity,
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity, Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn
} from 'typeorm';

// Note: this has some additional typing information (like width: 1 on bools and type: timestamps on
//   CreateDateColumn) to make the types generated here match what is generated by Laravel exactly.
//   At this time, we want TypeORM to expect exactly the same types that PHP uses by default. Tested
//   by checking what schema gets generated in the test database against the real DB during unit
//   test runs (the only time we let TypeORM modify the DB schema).
@Entity({ name: 'users' })
export class User extends BaseEntity {
  @PrimaryGeneratedColumn({ type: 'bigint', unsigned: true })
  id: number;

  // There are many rows in the prod DB without a UUID assigned, so this cannot be a unique
  // index until that is fixed.
  @Column({ type: 'char', width: 36 })
  @Index()
  uuid: string;

  @CreateDateColumn({ type: 'timestamp', name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamp', name: 'updated_at' })
  updatedAt: Date;

  @DeleteDateColumn({ type: 'timestamp', name: 'deleted_at' })
  deletedAt: Date;

  // TODO: relate this to the organisations table
  @Column({ type: 'bigint', name: 'organisation_id', nullable: true, unsigned: true })
  organisationId: number | null;

  @Column({ name: 'first_name', nullable: true })
  firstName: string | null;

  @Column({ name: 'last_name', nullable: true })
  lastName: string | null;

  @Column({ name: 'email_address', unique: true })
  emailAddress: string;

  @Column({ nullable: true })
  password: string | null;

  @Column({ name: 'email_address_verified_at', nullable: true })
  emailAddressVerifiedAt: Date | null;

  @Column({ name: 'last_logged_in_at', nullable: true })
  lastLoggedInAt: Date | null;

  @Column({ name: 'job_role', nullable: true })
  jobRole: string | null;

  @Column({ nullable: true })
  facebook: string | null;

  @Column({ nullable: true })
  twitter: string | null;

  @Column({ nullable: true })
  linkedin: string | null;

  @Column({ nullable: true })
  instagram: string | null;

  @Column({ nullable: true })
  avatar: string | null;

  @Column({ name: 'phone_number', nullable: true })
  phoneNumber: string | null;

  @Column({ name: 'whatsapp_phone', nullable: true })
  whatsappPhone: string | null;

  @Column({ width: 1, name: 'is_subscribed', default: true })
  isSubscribed: boolean;

  @Column({ width: 1, name: 'has_consented', default: true })
  hasConsented: boolean;

  @Column({ nullable: true })
  banners: string | null;

  @Column({ name: 'api_key', nullable: true })
  apiKey: string | null;

  @Column({ nullable: true })
  country: string | null;

  @Column({ nullable: true })
  program: string | null;

  @Column()
  locale: string;
}
