export const VALIDATION_TYPES = [
  "OVERLAPPING",
  "SELF_INTERSECTION",
  "POLYGON_SIZE",
  "SPIKES",
  "ESTIMATED_AREA",
  "DATA_COMPLETENESS",
  "PLANT_START_DATE",
  "DUPLICATE_GEOMETRY",
  "WITHIN_COUNTRY",
  "FEATURE_BOUNDS",
  "GEOMETRY_TYPE"
] as const;

export const NON_PERSISTENT_VALIDATION_TYPES: ValidationType[] = [
  "SELF_INTERSECTION",
  "POLYGON_SIZE",
  "SPIKES",
  "DUPLICATE_GEOMETRY",
  "DATA_COMPLETENESS",
  "FEATURE_BOUNDS",
  "GEOMETRY_TYPE"
] as const;

export type ValidationType = (typeof VALIDATION_TYPES)[number];

export const VALIDATION_CRITERIA_IDS = {
  OVERLAPPING: 3,
  SELF_INTERSECTION: 4,
  POLYGON_SIZE: 6,
  WITHIN_COUNTRY: 7,
  SPIKES: 8,
  ESTIMATED_AREA: 12,
  DATA_COMPLETENESS: 14,
  PLANT_START_DATE: 15,
  DUPLICATE_GEOMETRY: 16,
  FEATURE_BOUNDS: 5,
  GEOMETRY_TYPE: 10
} as const;

export const CRITERIA_ID_TO_VALIDATION_TYPE: Record<CriteriaId, ValidationType> = {
  3: "OVERLAPPING",
  4: "SELF_INTERSECTION",
  5: "FEATURE_BOUNDS",
  6: "POLYGON_SIZE",
  7: "WITHIN_COUNTRY",
  8: "SPIKES",
  10: "GEOMETRY_TYPE",
  12: "ESTIMATED_AREA",
  14: "DATA_COMPLETENESS",
  15: "PLANT_START_DATE",
  16: "DUPLICATE_GEOMETRY"
} as const;

export const EXCLUDED_VALIDATION_CRITERIA = [
  VALIDATION_CRITERIA_IDS.WITHIN_COUNTRY,
  VALIDATION_CRITERIA_IDS.ESTIMATED_AREA,
  VALIDATION_CRITERIA_IDS.PLANT_START_DATE
];

export type CriteriaId = (typeof VALIDATION_CRITERIA_IDS)[ValidationType];
