name: Services Deploy (all)
run-name: 'Services Deploy (all) [env: ${{ inputs.env }}]'

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment target environment'
        type: choice
        required: true
        options:
          - dev
          - test
          - staging
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  job-service:
    uses: ./.github/workflows/deploy-service.yml
    with:
      env: ${{ inputs.env }}
      service: job-service
    secrets: inherit

  user-service:
    uses: ./.github/workflows/deploy-service.yml
    with:
      env: ${{ inputs.env }}
      service: user-service
    secrets: inherit

  research-service:
    uses: ./.github/workflows/deploy-service.yml
    with:
      env: ${{ inputs.env }}
      service: research-service
    secrets: inherit


