name: Pull Request

env:
  HUSKY: 0
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  pull_request:

permissions:
  actions: read
  contents: read

# Note: we're disabling usage of NX Cloud. This does mean that all tests run every time, even
# if none of their dependent code changes, but it also means we don't have to pay for NX Cloud
# or go to NX Cloud to see test failures (they show on Github instead). If we get to a point
# where the full test suite is taking too long to run, we can explore paying for NX Cloud, but
# for now, this is fine.
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.29.1"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci --legacy-peer-deps

      - run: npx nx run-many -t lint build --no-cloud

      - name: Bring up DB Docker Container
        run: |
          docker-compose up -d
          ./docker/test-connection.sh

      # First run just the small database test to get the test database synced to the current schema
      # in a clean way.
      - name: Sync DB Schema
        run: npx nx test database --no-cloud --skip-nx-cache

      # All tests are run in band so that wipes of database tables from one test doesn't interfere
      # with other tests.
      - name: Test all
        run: npx nx run-many -t test --parallel=1 --no-cloud --coverage --runInBand --passWithNoTests --exclude database
